<a href="https://colab.research.google.com/github/aswathysaji/LEARN.PY/blob/main/TASK_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Generate a 3 x 3 matrix using random module.

In [1]:
#please provide your answer below this line.
import random

l=[ [ None for y in range( 3 ) ] for x in range( 3 ) ]
for i in range(3):
  for j in range(3):
    l[i][j]=random.randint(1,50)
print(l)

[[2, 22, 37], [42, 20, 6], [9, 47, 19]]


2. Generate two 4 x 4 matrix using numpy and 

 a) Reshape it to 2 x 8matrix and vertically stack it.

 b) Reshape it to 2 x 8 matrix and horizontally stack it.

In [2]:
#please provide your answer below this line.
import numpy as np

arr = np.array([[5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16],
                [17, 18, 19, 20]])
print(arr)
reshaped = np.reshape(arr, (2, 8))
print(np.vstack(reshaped))
print(np.hstack(reshaped))

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20]]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
